### PR TITLE
Update Jon Snow character info

### PR DESCRIPTION
**Pull request by chasebank**
Added 'King in the North' to titles.

Official citation: http://gameofthrones.com/game-of-thrones/season-6/episode-10/people/61/jon-snow

### CODE REVIEW

**Comment by joakimskoog** [comment]
Thank you! Does he still hold the title "Lord Commander of the Night's Watch" though?

**Comment by chasebank** [comment]
Good point. I don't believe so, and I wasn't sure if that's considered current titles, or all titles held past and present.

"The 998th Lord Commander of the Night's Watch" is listed under aliases. Personally, I think that's less of an alias, and more of an appropriate title. So it should be removed from aliases and used to replace the current Lord Commander title.

**Comment by joakimskoog** [comment]
That sounds great, could you please make a new pull request with that change included?

**Comment by joakimskoog** [comment]
Waiting for a new pull request with the additional changes, closing this one.

**Pull request closed without merging**
