### PR TITLE
Hodor's name

### PR DESCRIPTION
**Pull request by spoo-bar**
Added Hodor's name as Walder

### CODE REVIEW

**Comment by joakimskoog** [comment]
Just double checking: Is this book canon? If it is, I'll add it straight away.

**Comment by spoo-bar** [comment]
Yes, it was mentioned in the first book.

**Comment by joakimskoog** [comment]
Great, I'll merge it in a few minutes. Thank you for your contribution!

**Comment by joakimskoog** [comment]
This is now merged and live on the site, thank you!

**Pull request merged**
