### PR TITLE
Added `CoatOfArmsImage" field

### PR DESCRIPTION
**Pull request by fitomad**
The new field adds a reference to an image URL hosted on (A Wiki Of Ice and Fire)[http://awoiaf.westeros.org/]

The images are released under Creative Commons License.

Houses with the new field populate
- Stark
- Waterman
- Greyjoy
- Arryn
- Tully
- Lannister
- Seaworth

### CODE REVIEW

**Comment by joakimskoog** [comment]
Great work! I've just got a few thoughts:
- Should we really link to an external website? This can be quite error prone if they decide to change their URL scheme or similar. It would also be a bit douchey to steal their bandwidth.
- Are **all** the images released under Creative Commons?

What do you think about us hosting the images ourselves?

**Comment by fitomad** [comment]
Hi!
1. It's not mandatory, even preferred, to locate the images in your own server or CDN, but I don't know your hosting restrictions or conditions. For me It's OK host images in your server :) 
2. I'm not sure but I believe that all content inside [A Wiki of Ice and Fire](http://awoiaf.westeros.org) is under Creative License

Regards

**Comment by joakimskoog** [comment]
1. That's true. I host it on Azure, any thoughts on how we can host the images ourselves for a reasonable price? Maybe the Azure CDN?
2. Ok, that's great.

I think we should look for options to host the images ourselves, I'll get back to you after I've looked around a bit. You're welcome to do some research as well.

**Comment by joakimskoog** [comment]
Closing this for now, I don't have the money or the time to host all images on my own. Will look into this further in the future.

**Pull request closed without merging**
